#!/bin/bash

set -e
set -u
set -o pipefail

function g_exit() {
    echo Exiting...
    exit 1
}

while true; do
    read -p "Do you wish to install this program? [y/n] " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) g_exit;;
        * ) echo "Please answer 'y' for yes or 'n' for no.";;
    esac
done


set -x # enable xtrace
timedatectl set-ntp true

sed -i '/^#ParallelDownload/s/^.*$/ParallelDownloads = 9/' /etc/pacman.conf

pacstrap /mnt base linux linux-firmware \
    lvm2 \
    networkmanager \
    zsh \
    sudo \
    neovim \
    which \
    tree \
    git \
    base-devel

genfstab -U /mnt >> /mnt/etc/fstab

cp 3_in_chroot /mnt/root

arch-chroot /mnt
{ set +x; } 2> /dev/null # silently disable xtrace
